name: "Docker Release"

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: "Docker"
    uses: dosquad/actions/.github/workflows/docker-release.yml@main
    with:
      image: ghcr.io/na4ma4/ipmi-kvm-docker
      platforms: 'linux/amd64,'
      latest-on-branch: '{{is_default_branch}}'
    secrets:
      DOCKER_GITHUB_TOKEN: "${{ github.token }}"
